In [28]:
%pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (2.1.1)
Requirement already satisfied: scikit-learn in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.1.4)
Requirement already satisfied: six>=1.5 in c:\users\hasin\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd
import numpy as np

titanic_train = pd.read_csv('train.csv')
titanic_test = pd.read_csv('test.csv')

In [30]:
missing_values_count_train = titanic_train.isnull().sum()
missing_values_count_test = titanic_test.isnull().sum()
missing_values_count_train[0:12]
missing_values_count_test[0:12]

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [31]:
titanic_train.drop(['Cabin', 'Ticket', 'Name'], axis=1, inplace=True)
titanic_test.drop(['Cabin', 'Ticket', 'Name'], axis=1, inplace=True)

In [ ]:
titanic_train.dropna()
titanic_test.dropna()

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
409         1301       3  female   3.0      1      1   13.7750        S
411         1303       1  female  37.0      1      0   90.0000        Q
412         1304       3  female  28.0      0      0    7.7750        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S

[331 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
titanic_train['Sex'] = le.fit_transform(titanic_train['Sex'])
titanic_test['Sex'] = le.fit_transform(titanic_test['Sex'])

In [34]:
titanic_train = pd.get_dummies(titanic_train, columns=['Embarked'], drop_first=True)
titanic_test = pd.get_dummies(titanic_test, columns=['Embarked'], drop_first=True)
titanic_train.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,1,0,3,1,22.0,1,0,7.2500,False,True
1,2,1,1,0,38.0,1,0,71.2833,False,False
2,3,1,3,0,26.0,0,0,7.9250,False,True
3,4,1,1,0,35.0,1,0,53.1000,False,True
4,5,0,3,1,35.0,0,0,8.0500,False,True

In [35]:
titanic_test.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,892,3,1,34.5,0,0,7.8292,True,False
1,893,3,0,47.0,1,0,7.0000,False,True
2,894,2,1,62.0,0,0,9.6875,True,False
3,895,3,1,27.0,0,0,8.6625,False,True
4,896,3,0,22.0,1,1,12.2875,False,True

In [36]:
X_train = titanic_train.drop('Survived', axis=1)
y_train = titanic_train['Survived']
X_test = titanic_test